---
- name: Async Download JBoss EAP Patch from Red Hat Customer Portal
  redhat_csp_download:
    url: "{{ jboss_eap_patch_artifact_url }}"
    dest: "{{ jboss_eap_patch_dest }}"
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
  async: 7200
  poll: 0
  register: jboss_eap_patch_download
  tags:
    - jboss_eap

- name: Async Download JBoss EAP from Red Hat Customer Portal
  redhat_csp_download:
    url: "{{ jboss_eap_artifact_url }}"
    dest: "{{ jboss_eap_artifact_tmp_dest }}"
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
  async: 7200
  poll: 0
  register: jboss_eap_download
  tags:
    - jboss_eap

- name: 'Check On JBoss EAP Download Completion'
  async_status: jid={{ jboss_eap_download.ansible_job_id }}
  register: job_result1
  until: job_result1.finished
  retries: 600
  delay: 10
  tags:
    - jboss_eap

- name: 'Check On JBoss EAP Patch Download Completion'
  async_status: jid={{ jboss_eap_patch_download.ansible_job_id }}
  register: job_result2
  until: job_result2.finished
  retries: 600
  delay: 10
  tags:
    - jboss_eap