---

##
# As the EAP service would be named like jboss-as-standlone.sh or jboss-eap.sh
# the service ( directed via systemctl ) requires the service name to be without
# extension hence we use spiltext filter to get the service name wihout '.sh' extension
##
- name: Restart JBoss
  become: true
  service:
    name: "{{ jboss_eap_service_file }}"
    state: restarted

# Sanity test if everything was setup right and JBoss is running
- name: Verify JBoss is running
  wait_for: port="{{ instance_calculated_http_port }}" host="{{ instance_bind_address }}" timeout=120
  notify: Check JBoss is available

- name: Check JBoss is available
  uri:
    url: "http://{{ instance_bind_address }}:{{ instance_bind_address }}"
